on:
  workflow_call:
    inputs:
      RELEASE_REVISION:
        required: true
        type: string
      HELM_CHART_REPO:
        required: false
        type: string
      VALUES_LOCAL_PATH:
        required: false
        type: string
      ENVIRONMENT:
        required: true
        type: string
      KUBE_NAMESPACE:
        required: true
        type: string
      KUBE_CLUSTER:
        required: true
        type: string
      DEPLOYMENT:
        required: false
        type: string
      VALUES:
        required: false
        type: string

name: Build and push docker image

env:
  DEPLOYMENT: ${{ secrets.DEPLOYMENT }}
  VALUES_LOCAL_PATH: helm/chart
  HELM_CHART_REPO: s3://grokit-helm-charts
  VALUES: environment=${{ inputs.ENVIRONMENT }},app_version=${{ inputs.RELEASE_REVISION }}

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - name: Set chart repo name
      if: ${{ inputs.HELM_CHART_REPO }}
      run: echo "HELM_CHART_REPO=${{ inputs.HELM_CHART_REPO }}" >> $GITHUB_ENV

    - name: Set deployment name # if is different from secrets.DEPLOYMENT
      if: ${{ inputs.DEPLOYMENT }}
      run: echo "DEPLOYMENT=${{ inputs.DEPLOYMENT }}" >> $GITHUB_ENV

    - name: Set deployment name # if it's not helm/chart
      if: ${{ inputs.VALUES_LOCAL_PATH }}
      run: echo "VALUES_LOCAL_PATH=${{ inputs.VALUES_LOCAL_PATH }}" >> $GITHUB_ENV

    - name: Set values
      if: ${{ inputs.VALUES }}
      run: echo "VALUES=${{ inputs.VALUES }}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
   
    - name: Install s3 helm plugin
      uses: WyriHaximus/github-action-helm3@v2
      with: 
        exec: helm plugin install https://github.com/hypnoglow/helm-s3.git

    - name: Deploy chart
      uses: craftech-io/eks-helm-deploy-action@v2.0.1-rc1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        cluster-name: ${{ inputs.KUBE_CLUSTER }}
        chart-path: ${{ env.DEPLOYMENT }}/${{ env.DEPLOYMENT }}
        chart-repository:  ${{ env.HELM_CHART_REPO }}/${{ env.DEPLOYMENT }}
        name: ${{ env.DEPLOYMENT }}-${{ inputs.ENVIRONMENT }}
        namespace: ${{ inputs.ENVIRONMENT }}
        values: ${{ env.VALUES }}
        config-files: ${{ env.VALUES_LOCAL_PATH }}/env/values-${{ inputs.ENVIRONMENT }}.yaml
        chart-version: ${{ inputs.RELEASE_REVISION }}

